---
title: "Crime_FA"
author: "William"
date: "2023-08-09"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(psych)
library(corrplot)
library(ggplot2)
```

```{r}
crime <- read.csv("crime.csv", header=TRUE, row.names="X")
head(crime)
```

```{r}
KMO(r=cor(crime))
```



```{r}
cor(crime)
```


```{r}
datamatrix <- cor(crime)
corrplot(datamatrix, method="number")
```



```{r}
sapply(1:3, function(f) 
     factanal(crime, factors = f, method ="mle")$PVAL)
```

```{r}
crime.fa <- factanal(crime, factors = 3, method ="mle", scores = c("regression"), rotation = "varimax")
crime.fa
```



```{r}
crime.fa$uniquenesses
```


```{r}
apply(crime.fa$loadings^2,1,sum)
```



```{r}
1 - apply(crime.fa$loadings^2,1,sum)
```


```{r}
Lambda <- crime.fa$loadings
Psi <- diag(crime.fa$uniquenesses)
S <- crime.fa$correlation
Sigma <- Lambda %*% t(Lambda) + Psi
```



```{r}
round(S - Sigma, 6)
```

```{r}
fafitfree <- fa(crime,nfactors = ncol(crime), rotate = "none")
n_factors <- length(fafitfree$e.values)
scree     <- data.frame(
  Factor_n =  as.factor(1:n_factors), 
  Eigenvalue = fafitfree$e.values)
ggplot(scree, aes(x = Factor_n, y = Eigenvalue, group = 1)) + 
  geom_point() + geom_line() +
  xlab("Number of factors") +
  ylab("Initial eigenvalue") +
  labs( title = "Scree Plot")
```


```{r}
parallel <- fa.parallel(crime)
```



```{r}
(scores <- factanal(crime, factors = 3, method = "mle",
                    scores = "regression")$scores)
```


```{r}
cex <- 0.8
plot(scores[,1], scores[,2], type = "n", xlab = "Factor 1", ylab = "Factor 2")
text(scores[,1], scores[,2], abbreviate(rownames(crime), 3), cex = cex)
```



```{r}
life.none <- factanal(crime, factors = 3, rotation = "none")
life.varimax <- factanal(crime, factors = 3, rotation = "varimax")
life.promax <- factanal(crime, factors = 3, rotation = "promax")
```


```{r}
par(mfrow = c(1,3))
plot(life.none$loadings[,1], 
     life.none$loadings[,2],
     xlab = "Factor 1", 
     ylab = "Factor 2", 
     ylim = c(-1,1),
     xlim = c(-1,1),
     main = "No rotation")
text(life.varimax$loadings[,1]-0.08, 
     life.varimax$loadings[,2]+0.08,
      colnames(crime),
      col="red")
abline(h = 0, v = 0)

plot(life.varimax$loadings[,1], 
     life.varimax$loadings[,2],
     xlab = "Factor 1", 
     ylab = "Factor 2", 
     ylim = c(-1,1),
     xlim = c(-1,1),
     main = "Varimax rotation")

text(life.varimax$loadings[,1]-0.08, 
     life.varimax$loadings[,2]+0.08,
      colnames(crime),
      col="blue")
abline(h = 0, v = 0)

plot(life.promax$loadings[,1], 
     life.promax$loadings[,2],
     xlab = "Factor 1", 
     ylab = "Factor 2",
     ylim = c(-1,1),
     xlim = c(-1,1),
     main = "Promax rotation")
text(life.varimax$loadings[,1]-0.08, 
     life.varimax$loadings[,2]+0.08,
      colnames(crime),
      col="green")
abline(h = 0, v = 0)
```



```{r}
par(mfrow = c(1,3))
plot(life.none$loadings[,1], 
     life.none$loadings[,3],
     xlab = "Factor 1", 
     ylab = "Factor 3", 
     ylim = c(-1,1),
     xlim = c(-1,1),
     main = "No rotation")
text(life.varimax$loadings[,1]-0.08, 
     life.varimax$loadings[,3]+0.08,
      colnames(crime),
      col="red")
abline(h = 0, v = 0)

plot(life.varimax$loadings[,1], 
     life.varimax$loadings[,3],
     xlab = "Factor 1", 
     ylab = "Factor 3", 
     ylim = c(-1,1),
     xlim = c(-1,1),
     main = "Varimax rotation")

text(life.varimax$loadings[,1]-0.08, 
     life.varimax$loadings[,3]+0.08,
      colnames(crime),
      col="blue")
abline(h = 0, v = 0)

plot(life.promax$loadings[,1], 
     life.promax$loadings[,3],
     xlab = "Factor 1", 
     ylab = "Factor 3",
     ylim = c(-1,1),
     xlim = c(-1,1),
     main = "Promax rotation")
text(life.varimax$loadings[,1]-0.08, 
     life.varimax$loadings[,3]+0.08,
      colnames(crime),
      col="green")
abline(h = 0, v = 0)
```






```{r}
loads <- crime.fa$loadings
fa.diagram(loads)
```




