```{r}
df <- read.csv("USArrests.csv",header=TRUE)
df
```
```{r}
m1 <- cbind(c(31,79,51,14), c(67,42,50,43),c(14,25,90,91),c(69,91,57,92))
m1
```
```{r}
results <- princomp(m1,cor=TRUE,scores = TRUE)
summary(results, loadings = TRUE)
```
```{r}
plot(results$sdev^2/sum(results$sdev^2), xlab = "Component number",
     ylab = "Component proportion", type = "b", main = "Scree diagram")
```
```{r}
cumulative_variance <- cumsum(results$sdev^2) / sum(results$sdev^2)

```
```{r}
plot(1:length(results$sdev), cumulative_variance, type = "b",
     xlab = "Principal Component (PC)", ylab = "Cumulative Variance Explained",
     main = "Cumulative Scree Plot for PCA")
```
```{r}
max(df$Murder)
```
```{r}
boxplot(df$Murder, main = "Boxplot of Murder")
```
```{r}
boxplot(df$Assault, main = "Boxplot of Assault")

```
```{r}
boxplot(df$Rape, main = "Boxplot of Rape")

```
```{r}
dfn <- df[,-1]
dfn
```

```{r}
results <- princomp(dfn,cor=TRUE,scores = TRUE)
summary(results, loadings = TRUE)
```
```{r}
cumulative_variance <- cumsum(results$sdev^2) / sum(results$sdev^2)

```
```{r}
plot(1:length(results$sdev), cumulative_variance, type = "b",
     xlab = "Principal Component (PC)", ylab = "Cumulative Variance Explained",
     main = "Cumulative Scree Plot for PCA")
```

```{r}
biplot(results)
```



